import { Appearance } from "@clerk/types";

export const clerkAppearance: Appearance = {
  layout: {
    socialButtonsVariant: "blockButton",
    socialButtonsPlacement: "bottom",
    showOptionalFields: true,
    termsPageUrl: undefined,
    privacyPageUrl: undefined,
    helpPageUrl: undefined,
  },
  variables: {
    colorPrimary: "#8b5cf6",
    colorBackground: "#FAF7F3",
    colorInputBackground: "#FFFFFF",
    colorInputText: "#3D2F2C",
    colorText: "#3D2F2C",
    colorTextSecondary: "#7D6F6C",
    colorDanger: "#DC6B65",
    colorSuccess: "#7CB68E",
    colorWarning: "#E8A87C",
    borderRadius: "1rem",
    fontFamily: "var(--font-geist-sans)",
    fontSize: "0.9375rem",
  },
  elements: {
    card: "shadow-warm border-0 bg-white",
    headerTitle: "text-2xl font-bold text-purple-900",
    headerSubtitle: "text-neutral-600",
    socialButtonsBlockButton: "border-2 border-neutral-200 hover:border-purple-300 hover:bg-purple-50 transition-all duration-300",
    formButtonPrimary:
      "bg-purple-600 hover:bg-purple-700 text-white font-semibold py-3.5 px-6 rounded-2xl transition-all duration-300 shadow-warm hover:shadow-warm-lg hover:-translate-y-0.5",
    formFieldInput:
      "border-2 border-neutral-200 bg-white rounded-2xl px-4 py-3.5 focus:ring-2 focus:ring-purple-400 focus:border-purple-400 hover:border-neutral-300 transition-all duration-300",
    formFieldLabel: "text-sm font-semibold text-neutral-700",
    footerActionLink: "text-purple-600 hover:text-purple-700 font-semibold",
    identityPreviewText: "text-sm font-medium text-neutral-700",
    identityPreviewEditButton: "text-purple-600 hover:text-purple-700",
    formHeaderTitle: "text-xl font-bold text-purple-900",
    formHeaderSubtitle: "text-neutral-600 text-sm",
    dividerLine: "bg-gradient-to-r from-transparent via-neutral-300 to-transparent",
    dividerText: "text-neutral-500 text-sm font-medium",
    formFieldInputShowPasswordButton: "text-neutral-500 hover:text-neutral-700",
    formFieldError: "text-red-600 text-sm font-medium",
    alertText: "text-sm",
    formResendCodeLink: "text-purple-600 hover:text-purple-700 text-sm font-semibold",
    otpCodeFieldInput:
      "border-2 border-neutral-200 bg-white rounded-2xl text-center font-mono text-lg focus:ring-2 focus:ring-purple-400",
    footer: {
      display: "none",
    },
    userButtonPopoverFooter: {
      display: "none",
    },
    userButtonAvatarBox: "border-3 border-purple-200 shadow-warm",
    userButtonPopoverCard: "shadow-warm-lg border-0 rounded-3xl bg-white",
    userButtonPopoverActionButton: "hover:bg-purple-50 rounded-xl transition-all duration-300",
    userButtonPopoverActionButtonText: "text-neutral-700 font-medium",
    userButtonPopoverActionButtonIcon: "text-purple-600",
    modalBackdrop: "bg-neutral-900/40 backdrop-blur-sm",
    modalContent: "shadow-warm-xl rounded-3xl border-0 bg-white",
    modalCloseButton: "text-neutral-500 hover:text-neutral-700",
    profileSectionPrimaryButton:
      "bg-purple-600 hover:bg-purple-700 text-white font-semibold py-3 px-5 rounded-2xl transition-all duration-300 shadow-warm",
    profileSectionContent: "text-neutral-600",
    profileSectionTitle: "text-xl font-bold text-purple-900",
    profileSectionTitleText: "text-xl font-bold text-purple-900",
    navbar: "border-b border-neutral-200",
    navbarButton: "text-neutral-600 hover:text-purple-600 font-medium",
    navbarButtonIcon: "text-purple-600",
    accordionTriggerButton: "hover:bg-purple-50 rounded-xl transition-all duration-300",
    button: "font-semibold transition-all duration-300",
    buttonArrowIcon: "text-purple-600",
    menuList: "border-0 shadow-warm-lg rounded-2xl bg-white",
    menuItem: "hover:bg-purple-50 rounded-xl transition-all duration-300",
    badge: "bg-purple-100 text-purple-700 font-semibold rounded-xl",
    backLink: "text-purple-600 hover:text-purple-700 font-semibold",
  },
};
